sonar.projectKey=acaro-org
sonar.projectName=ACARO.org
sonar.sourceEncoding=UTF-8
sonar.sources=backend/src,frontend/app,frontend/components,frontend/context,frontend/lib,frontend/data,frontend/scripts
sonar.tests=backend/__tests__
sonar.exclusions=**/node_modules/**,**/.next/**,**/coverage/**,**/*.min.js,**/*.d.ts
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info
