import {
  Activity,
  AlertCircle,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Archive,
  BarChart,
  Ban,
  Building2,
  CalendarDays,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  CircleX,
  ClipboardList,
  Clock,
  Copy,
  Pencil,
  FileText,
  Eye,
  EyeOff,
  FolderOpen,
  GitBranch,
  GitBranchPlus,
  HardHat,
  Home,
  Inbox,
  LayoutDashboard,
  Leaf,
  Link,
  ListChecks,
  Lock,
  Mail,
  Megaphone,
  MessageSquare,
  Phone,
  PieChart,
  Plus,
  Power,
  RefreshCw,
  RotateCw,
  Search,
  SearchX,
  Send,
  ShieldCheck,
  Sparkles,
  Star,
  Terminal,
  ToggleLeft,
  Trash2,
  TrendingUp,
  Undo2,
  User,
  UserCog,
  UserRoundX,
  Users,
  X,
  Coffee,
  Info,
  Droplet,
  Download,
  ExternalLink,
  QrCode,
  TreePine,
  type LucideIcon,
} from "lucide-react"

import { cn } from "@/lib/utils"

const icons: Record<string, LucideIcon> = {
  account_tree: GitBranch,
  account_tree_off: GitBranchPlus,
  add: Plus,
  arrow_back: ArrowLeft,
  arrow_downward: ArrowDown,
  arrow_forward: ArrowRight,
  arrow_upward: ArrowUp,
  assignment_return: Undo2,
  assignment: ClipboardList,
  admin_panel_settings: ShieldCheck,
  bar_chart: BarChart,
  block: Ban,
  calendar_month: CalendarDays,
  calendar_today: CalendarDays,
  call: Phone,
  campaign: Megaphone,
  cancel: CircleX,
  check: Check,
  check_circle: CheckCircle2,
  chevron_left: ChevronLeft,
  close: X,
  content_copy: Copy,
  contract_edit: Pencil,
  corporate_fare: Building2,
  dashboard: LayoutDashboard,
  delete: Trash2,
  description: FileText,
  download: Download,
  draft: FileText,
  edit: Pencil,
  engineering: HardHat,
  eco: Leaf,
  error: AlertCircle,
  error_outline: AlertCircle,
  filter_list: ClipboardList,
  folder_open: FolderOpen,
  groups: Users,
  home: Home,
  inventory_2: Archive,
  link: Link,
  open_in_new: ExternalLink,
  lock: Lock,
  mail: Mail,
  newspaper: FileText,
  power_settings_new: Power,
  person: User,
  progress_activity: RotateCw,
  publish: Send,
  qr_code: QrCode,
  refresh: RefreshCw,
  search: Search,
  search_off: SearchX,
  send: Send,
  star: Star,
  terminal: Terminal,
  unarchive: Inbox,
  visibility: Eye,
  visibility_off: EyeOff,
  manage_accounts: UserCog,
  do_not_disturb_on: UserRoundX,
  web: Eye,
  activity: Activity,
  chevron_down: ChevronDown,
  clock: Clock,
  list_checks: ListChecks,
  message_square: MessageSquare,
  pie_chart: PieChart,
  sparkles: Sparkles,
  toggle_left: ToggleLeft,
  trending_up: TrendingUp,
  coffee: Coffee,
  info: Info,
  water: Droplet,
  trees: TreePine,
}

type AppIconProps = {
  name: string
  className?: string
  decorative?: boolean
}

export function AppIcon({ name, className, decorative = true }: AppIconProps) {
  const Icon = icons[name] ?? AlertCircle

  return (
    <Icon
      className={cn("inline-block h-[1em] w-[1em] shrink-0", className)}
      aria-hidden={decorative ? "true" : undefined}
    />
  )
}
