-- GENERADO DESDE panama-distritos.geojson
INSERT INTO distritos_panama (codigo_distrito, provincia, distrito)
VALUES
  ('0101', 'Bocas del Toro', 'Bocas del Toro'),
  ('0102', 'Bocas del Toro', 'Changuinola'),
  ('0103', 'Bocas del Toro', 'Chiriquí Grande'),
  ('0104', 'Bocas del Toro', 'Almirante'),
  ('0201', 'Coclé', 'Aguadulce'),
  ('0202', 'Coclé', 'Antón'),
  ('0203', 'Coclé', 'La Pintada'),
  ('0204', 'Coclé', 'Natá'),
  ('0205', 'Coclé', 'Olá'),
  ('0206', 'Coclé', 'Penonomé'),
  ('0301', 'Colón', 'Colón'),
  ('0302', 'Colón', 'Chagres'),
  ('0303', 'Colón', 'Donoso'),
  ('0304', 'Colón', 'Portobelo'),
  ('0305', 'Colón', 'Santa Isabel'),
  ('0306', 'Colón', 'Omar Torrijos Herrera'),
  ('0401', 'Chiriquí', 'Alanje'),
  ('0402', 'Chiriquí', 'Barú'),
  ('0403', 'Chiriquí', 'Boquerón'),
  ('0404', 'Chiriquí', 'Boquete'),
  ('0405', 'Chiriquí', 'Bugaba'),
  ('0406', 'Chiriquí', 'David'),
  ('0407', 'Chiriquí', 'Dolega'),
  ('0408', 'Chiriquí', 'Gualaca'),
  ('0409', 'Chiriquí', 'Remedios'),
  ('0410', 'Chiriquí', 'Renacimiento'),
  ('0411', 'Chiriquí', 'San Félix'),
  ('0412', 'Chiriquí', 'San Lorenzo'),
  ('0413', 'Chiriquí', 'Tolé'),
  ('0414', 'Chiriquí', 'Tierras Altas'),
  ('0501', 'Darién', 'Chepigana'),
  ('0502', 'Darién', 'Pinogana'),
  ('0503', 'Darién', 'Santa Fe'),
  ('0601', 'Herrera', 'Chitré'),
  ('0602', 'Herrera', 'Las Minas'),
  ('0603', 'Herrera', 'Los Pozos'),
  ('0604', 'Herrera', 'Ocú'),
  ('0605', 'Herrera', 'Parita'),
  ('0606', 'Herrera', 'Pesé'),
  ('0607', 'Herrera', 'Santa María'),
  ('0701', 'Los Santos', 'Guararé'),
  ('0702', 'Los Santos', 'Las Tablas'),
  ('0703', 'Los Santos', 'Los Santos'),
  ('0704', 'Los Santos', 'Macaracas'),
  ('0705', 'Los Santos', 'Pedasí'),
  ('0706', 'Los Santos', 'Pocrí'),
  ('0707', 'Los Santos', 'Tonosí'),
  ('0802', 'Panamá', 'Balboa'),
  ('0805', 'Panamá', 'Chepo'),
  ('0806', 'Panamá', 'Chimán'),
  ('0808', 'Panamá', 'Panamá'),
  ('0810', 'Panamá', 'San Miguelito'),
  ('0811', 'Panamá', 'Taboga'),
  ('0901', 'Veraguas', 'Atalaya'),
  ('0902', 'Veraguas', 'Calobre'),
  ('0903', 'Veraguas', 'Cañazas'),
  ('0904', 'Veraguas', 'La Mesa'),
  ('0905', 'Veraguas', 'Las Palmas'),
  ('0906', 'Veraguas', 'Montijo'),
  ('0907', 'Veraguas', 'Río de Jesús'),
  ('0908', 'Veraguas', 'San Francisco'),
  ('0909', 'Veraguas', 'Santa Fe'),
  ('0910', 'Veraguas', 'Santiago'),
  ('0911', 'Veraguas', 'Soná'),
  ('0912', 'Veraguas', 'Mariato'),
  ('1000', 'Comarca Kuna Yala', 'No asignado'),
  ('1101', 'Comarca Emberá Wounaán', 'Cémaco (Área 1)'),
  ('1102', 'Comarca Emberá Wounaán', 'Sambú (Área 2)'),
  ('1201', 'Comarca Ngäbe Buglé', 'Besiko'),
  ('1202', 'Comarca Ngäbe Buglé', 'Mironó'),
  ('1203', 'Comarca Ngäbe Buglé', 'Müna'),
  ('1204', 'Comarca Ngäbe Buglé', 'Nole Duima'),
  ('1205', 'Comarca Ngäbe Buglé', 'Ñürün'),
  ('1206', 'Comarca Ngäbe Buglé', 'Kankintú'),
  ('1207', 'Comarca Ngäbe Buglé', 'Kusapín'),
  ('1208', 'Comarca Ngäbe Buglé', 'Jirondai'),
  ('1209', 'Comarca Ngäbe Buglé', 'Santa Catalina o Calovébora'),
  ('1301', 'Panamá Oeste', 'Arraiján'),
  ('1303', 'Panamá Oeste', 'Capira'),
  ('1304', 'Panamá Oeste', 'Chame'),
  ('1307', 'Panamá Oeste', 'La Chorrera'),
  ('1309', 'Panamá Oeste', 'San Carlos')
ON DUPLICATE KEY UPDATE
  provincia = VALUES(provincia),
  distrito = VALUES(distrito);
